// <auto-generated />
using MBMTrans.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MBMTrans.Migrations
{
    [DbContext(typeof(BaseContext))]
    partial class BaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("MBMTrans.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CompanyId");

                    b.Property<string>("Email");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<int?>("RoleId");

                    b.Property<string>("Surname");

                    b.Property<string>("Token");

                    b.Property<string>("Verificated");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MBMTrans.Models.Auto.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ColorId");

                    b.Property<int?>("ManufactureId");

                    b.Property<int?>("ModelId");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ManufactureId");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("MBMTrans.Models.Auto.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("MBMTrans.Models.Auto.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<int?>("CarId");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("MBMTrans.Models.Auto.Manufacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Manufactures");
                });

            modelBuilder.Entity("MBMTrans.Models.Auto.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ManufactureId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ManufactureId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("MBMTrans.Models.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ColorId");

                    b.Property<string>("Comments");

                    b.Property<string>("Image");

                    b.Property<int?>("ManufactureId");

                    b.Property<int?>("ModelId");

                    b.Property<string>("Name");

                    b.Property<string>("Period");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ManufactureId");

                    b.HasIndex("ModelId");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("MBMTrans.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.Property<string>("Sity");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("MBMTrans.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("EndAddress");

                    b.Property<string>("StartAddress");

                    b.Property<decimal>("Symmary");

                    b.Property<int?>("TariffId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TariffId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MBMTrans.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MBMTrans.Models.Tariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("MBMTrans.Models.Account", b =>
                {
                    b.HasOne("MBMTrans.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("MBMTrans.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("MBMTrans.Models.Auto.Car", b =>
                {
                    b.HasOne("MBMTrans.Models.Auto.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId");

                    b.HasOne("MBMTrans.Models.Auto.Manufacture", "Manufacture")
                        .WithMany("Cars")
                        .HasForeignKey("ManufactureId");

                    b.HasOne("MBMTrans.Models.Auto.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId");
                });

            modelBuilder.Entity("MBMTrans.Models.Auto.Driver", b =>
                {
                    b.HasOne("MBMTrans.Models.Account", "Account")
                        .WithMany("Drivers")
                        .HasForeignKey("AccountId");

                    b.HasOne("MBMTrans.Models.Auto.Car", "Car")
                        .WithOne("Driver")
                        .HasForeignKey("MBMTrans.Models.Auto.Driver", "CarId");
                });

            modelBuilder.Entity("MBMTrans.Models.Auto.Model", b =>
                {
                    b.HasOne("MBMTrans.Models.Auto.Manufacture", "Manufacture")
                        .WithMany("Models")
                        .HasForeignKey("ManufactureId");
                });

            modelBuilder.Entity("MBMTrans.Models.Catalog", b =>
                {
                    b.HasOne("MBMTrans.Models.Auto.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("MBMTrans.Models.Auto.Manufacture", "Manufacture")
                        .WithMany()
                        .HasForeignKey("ManufactureId");

                    b.HasOne("MBMTrans.Models.Auto.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");
                });

            modelBuilder.Entity("MBMTrans.Models.Order", b =>
                {
                    b.HasOne("MBMTrans.Models.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId");

                    b.HasOne("MBMTrans.Models.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId");
                });
#pragma warning restore 612, 618
        }
    }
}
